Write a Python Program to find sum of array?

In [11]:
def sum_array(ar1,ar2):
    import numpy as np
    return np.array(ar1)+np.array(ar2)
l=[1,2,5,6,6,7,4]
l1=[4,5,565,544,656,5656,67]
sum_array(l,l1)
   

array([   5,    7,  570,  550,  662, 5663,   71])

2. Write a Python Program to find largest element in an array?

In [19]:
def large_el(ar1):
    import numpy as np
    return np.max(ar1)
l=[1,2,5,6,6,7,4]
large_el(l)
    
    
    

7

3. Write a Python Program for array rotation?

In [107]:
def arr_rotate(l):
    l1=[]
    k=int(input("left to right movement:"))
    import numpy as np
    l=np.array(l)
    for i in range(len(l)):
        s=i-k
        o=(l[s])
        l1.append(o)
    return np.array(l1)
    
l=[1,2,5,6,6,7,4]
arr_rotate(l)
    
   

left to right movement:5


array([5, 6, 6, 7, 4, 1, 2])

In [112]:
def arr_rotate_2(l):
    l1=[]
    k=int(input("right to left movement:"))
    import numpy as np
    l=np.array(l)
    for i in range(len(l)):
        p=len(l)-k
        s=i-p
        o=l[s]
        l1.append(o)
    return np.array(l1)
l=[1,2,5,6,6,7,4]
arr_rotate_2(l)
    
        
   


right to left movement:2


array([5, 6, 6, 7, 4, 1, 2])

Write a Python Program to Split the array and add the first part to the end?

In [113]:
def split_array(l):
    l1=[]
    k=int(input("no. of elements to be split:"))
    import numpy as np
    l=np.array(l)
    for i in range(len(l)):
        p=len(l)-k
        s=i-p
        o=l[s]
        l1.append(o)
    return np.array(l1)
l=[1,2,5,6,6,7,4]
split_array(l)
    

    
    

no. of elements to be split:3


array([6, 6, 7, 4, 1, 2, 5])

5. Write a Python Program to check if given array is Monotonic?


In [118]:
def monotonic(a):
    return(all(a[i]<= a[i+1] for i in range(len(a)-1)) or all(a[i]>= a[i+1] for i in range(len(a)-1)) )
m=[4556,7890,987]
monotonic(m)

False